### ISSUE TITLE
readme命令的写法可以再规范一些

### ISSUE THREAD

**Issue by hua-zhi-wan** [XKaguya/zhenxun_otto_hzys_plugin#1]
rt，可以参考一下一些linux命令里的help是怎么写的。这个东西似乎有一套完整的规范。

**Comment by XKaguya** [comment]
> rt，可以参考一下一些linux命令里的help是怎么写的。这个东西似乎有一套完整的规范。

好的，谢谢佬，我研究研究怎么写规范一些

**Comment by XKaguya** [comment]
> rt，可以参考一下一些linux命令里的help是怎么写的。这个东西似乎有一套完整的规范。

改了一下，佬觉得现在呢？
